accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.password, name='password'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

insta/urls.py
from django.contrib import admin
from django.urls import path, include

#upload setting
from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views
from posts import views as posts_views

urlpatterns = [
    path('', posts_views.list, name='root'),
    path('admin/asdf/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:username>', accounts_views.people, name="people"),
    
]


# Dev only
# static(통과하고자 하는 url, 실제 저장 장소)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name="posts"


urlpatterns = [
        path('create/', views.create, name='create'),
        path('', views.list, name="list"),
        path('<int:post_id>/', views.delete, name='delete'),
        path('<int:post_id>/update/', views.update, name='update'),
        path('<int:post_id>/like/', views.like, name='like'),
        path('<int:post_id>/comment/create', views.comment_create, name='comment_create'),
        path('<int:post_id>/<int:comment_id>/delete', views.comment_delete, name='comment_delete'),
    ]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# 1:1
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.TextField()
    nickname = models.CharField(max_length=20)
    image = models.ImageField(blank=True)
    

class User(AbstractUser):
    followings = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followed_by")
    

posts/models.py
from django.db import models
#from django.contrib.auth.models import User 직접 접근
from django.conf import settings
from django_extensions.db.models import TimeStampedModel
# django.conf~~!!!!


# Create your models here.
class Post(TimeStampedModel):
    content = models.CharField(max_length=220)
    image = models.ImageField(blank=True)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts', blank=True)
    
    def __str__(self):
        return f"{self.id}: {self.content}"
    
    
class Comment(TimeStampedModel):
    content = models.CharField(max_length=140)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=False)
    
    def __str__(self):
        return f"{self.user}-{self.post}: {self.content}"


# class Comment_Response(models.Model):
#     content = models.CharField(max_length=140)
#     comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='reponses')
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=False)
#     def __str__(self):
#         return f"{self.id}: {self.content}"

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
# from django.contrib.auth.model
from django.forms import ModelForm
from .models import Profile

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email','last_name','first_name')


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('description', 'nickname','image',)
        

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        # fields = UserCreationForm.Meta.fields

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm, PasswordChangeForm
from .forms import CustomUserChangeForm, ProfileForm, CustomUserCreationForm

from django.contrib.auth import get_user_model

from django.contrib.auth import update_session_auth_hash
from .models import Profile

from django.core.exceptions import ObjectDoesNotExist
from posts.forms import CommentModelForm

# Create your views here.

from IPython import embed

def login(request):
    
    if request.method == "GET":
        '''
        form = AuthenticationForm()
        reutnr render(request, 'accounts/login.html', {'form':form})
        '''
        return render(request, 'accounts/login.html')
    else:
        
        '''
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('posts:list')
        '''
        
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username, password=password)
        if user:
            auth_login(request, user)
            return redirect(request.GET.get('next') or 'posts:list')
        else:
            return redirect('accounts:login')
    

def logout(request):
    auth_logout(request)
    return redirect('posts:list')


def signup(request):
    
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)  ## 동시에 1:1 레코드 생기도록.
            auth_login(request, user)
            return redirect('posts:list')
    else:
        form = CustomUserCreationForm()
        
    return render(request,'accounts/signup.html',{'form':form})
        

def people(request, username):
    
    people = get_object_or_404(get_user_model(), username=username)
    profile = get_object_or_404(Profile, user=people)
    # 1. settings.AUTH_USER_MODEL (django.conf)
    # 2. get_user_model() (django.contrib.auth)  ## recommended~!
    # 사용 지양할 것. ### 3. User (django.contrib.auth.models.User) ### 안쓰는게 좋음.
    comment_form = CommentModelForm()
    return render(request, 'accounts/people.html', {
        'people':people,
        'comment_form':comment_form,
        'profile':profile
    })


# 회원 정보 변경(편집 & 반영)
def update(request):
    if request.method == "POST":
        user_change_form = CustomUserChangeForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        
        if user_change_form.is_valid() and profile_form.is_valid():
            user = user_change_form.save()
            profile_form.save()
            #user = user_change_form.get_user()
            
            return redirect('people', user.username)
    else:
        user_change_form = CustomUserChangeForm(instance=request.user)
        profile, created = Profile.objects.get_or_create(user=request.user)
        
        profile_form = ProfileForm(instance=request.user.profile)
        
        # if hasattr(request.user, 'profile'):
        #     profile_form = ProfileForm(instance=request.user.profile)
        # else:
        #     profile_form = Profile.objects.create(user=request.user)
        
        return render(request, 'accounts/update.html', {
            'user_change_form':user_change_form,
            'profile_form':profile_form
        })


def delete(request):
    if request.method == "POST":
        request.user.delete()
        return redirect('posts:list')

    return render(request, 'accounts/delete.html')
    
    
def password(request):
    if request.method == "POST":
        password_change_form = PasswordChangeForm(request.user, request.POST)
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)
            return redirect('people', request.user.username)
    else:
        password_change_form = PasswordChangeForm(request.user)
        return render(request, 'accounts/password.html',
        {
            'password_change_form':password_change_form
            
        })


def follow(request, user_id):
    followed = get_object_or_404(get_user_model(), pk=user_id) # one who is followed
    
    # 만약 현재 유저가 해당 유저를 이미 팔로우 하고 있었으면, 
    if followed in request.user.followings.all():
    #   -> 팔로우를 취소
        request.user.followings.remove(followed)
    else: # 아니면,
    #   -> 팔로우
        request.user.followings.add(followed)
        
    return redirect('people', followed.username)
    

accounts/templates/accounts/delete.html
{% extends 'base.html' %}


{% block body %}
  <form method="POST">
    {% csrf_token  %}
    <p>정말로 탈퇴?!</p>
    <button class="btn btn-danger" onclick="return confirm('정말 삭제?!')">탈퇴하기</button>
  </form>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}

  <div class="row justify-content-center">
    <form method="POST">
      {% csrf_token %}
      <!--<div class="form-group">-->
      <!--  <label for="exampleInputEmail1">Email address</label>-->
      <!--  <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" name="username">-->
      <!--  <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
      <!--</div>-->
      
      <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Enter id" name="username">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="password">
      </div>
      <!--<div class="form-group form-check">-->
      <!--  <input type="checkbox" class="form-check-input" id="exampleCheck1">-->
      <!--  <label class="form-check-label" for="exampleCheck1">Check me out</label>-->
      <!--</div>-->
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
  </div>

{% endblock %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

<form method="POST">
    {% csrf_token %}
    
    <button class="btn btn-primary">비밀번호 변경</button>
    
    {% bootstrap_form password_change_form %}
</form>

{% endblock %}

accounts/templates/accounts/people.html
{% extends 'base.html' %}
{% load static  %}

{% block title  %}
{{people.username}} Myinstagram
{% endblock  %}

{% block body %}

<link rel="stylesheet" href="{% static 'accounts/css/style.css' %}" type="text/css" />


<div class="row mt-3">
  <div class="col-lg-3">
    <!-- User profile Photo  -->
    {% if profile.image %}
    <img src="{{profile.image.url}}" height="200" width="200" style="border-radius:50%"></img>
    {% else %}
      <!-- 수정페이지로  -->
      <a href="#"><img src="{% static 'accounts/img/default_user.png'%}" height="200" width="200" style="border-radius:50%"></img></a>
    {% endif  %}
  </div>
  <div class="col-lg-9">
    <div class="container-fluid m-0 p-0">
      <div class="row">
        <div class="col-lg-2">
          <h2>{{ people.username }}</h2>
        </div>
        {% if people != user and user.is_authenticated  %}
        <div class="col-lg-2">
          {% if user in people.followed_by.all %}
            <a class = "btn btn-outline-dark " href="{% url 'accounts:follow' people.id %}">팔로잉</a>
          {% else %}
              <a class = "btn btn-outline-dark" href="{% url 'accounts:follow' people.id %}">팔로우</a>
          {% endif  %}
        </div>
        {% endif %}
        <div class="col-lg-2">
          {% if user == people %}
            <a href="{% url 'accounts:update' %}" class="btn btn-outline-dark">프로필 편집</a>
          {% endif  %}
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-sm-3">게시물 {{people.post_set.count}}</div>
      <div class="col-sm-3">팔로우 {{people.followings.count}}</div>
      <div class="col-sm-3">팔로워 {{people.followed_by.count}}</div>
    </div>
    <div class="conatiner-fluid m-0 p-0">
      <div class="row pl-2">
        <strong>{{people.last_name}}  {{people.first_name}}</strong>
      </div>
      <div class="row pl-3">
        <p>{{people.profile.nickname}}</p>
      </div>
      <div class="row pl-3">
        <p>{{people.profile.description}}</p>
      </div>
    </div>
  </div>
  
</div>
    
<hr>
  
<div>

  
  {% if user == people %}
  <a href="{% url 'accounts:password' %}" class="btn btn-info">비밀번호 변경</a>
  <a href="{% url 'accounts:delete' %}" class="btn btn-danger">회원탈퇴 </a>
  {% endif  %}
  
  
  <div class="card-columns mt-3">
    {% for post in people.post_set.all %}
    
      {% if post.image  %}
      <div class="card" data-toggle="modal" data-target="#modal{{post.id}}">
            <img src="{{ post.image.url }}" class="img-fluid card-img-top"></img>
      </div>
      
      <!-- Modal -->

      <div class="modal fade" id="modal{{post.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content m-0 p-0">
            <div class="modal-body m-0 p-0">
              <div class="conatiner-fluid h-100">
                <div class="row h-100">
                  <div class="col d-flex align-items-center">
                    
                    <!-- Image Part  -->
                    <img src="{{ post.image.url }}" class="img-fluid m-0 p-0"></img>
                    
                  </div>
                  <div class="col">
                    <!-- Content Part  -->
                    <div class="row">
                      <div>
                      <i class="far fa-user-circle"></i>
                      </div>
                      <div>
                      <strong>{{post.user.username}}</strong>
                      </div>
                    </div>
                    <div class="row">
                      <p>{{post.content}}</p>
                    </div>
                    
                    <div class="row">
                      <a href="{% url 'posts:like' post.id %}">
                        <!-- 해당유저가 like를 했으면   -->
                        {% if user in post.like_users.all %}
                          <i class="fas fa-heart"></i>
                        {% else %}
                        <!-- 아니면  -->
                          <i class="far fa-heart"></i>
                        {% endif %}
                      </a>
                      <a href="#"><i class="far fa-comment-alt"></i></a>
                      <a href="#"><i class="far fa-share-square"></i></a>
                      
                      <p class="card-text">
                        좋아요 {{post.like_users.count}}개
                      </p>
                    </div>
                    
                    <!-- 해당글에 작성된 댓글을 모두 출력  -->
                    {% for com in post.comments.all  %}
                      <div>
                        <strong>{{com.user.username}}</strong>: {{com.content}}
                        <!--<a href="{% url 'posts:like' post.id %}">-->
                           <!--해당유저가 like를 했으면   -->
                        <!--  {% if user in post.like_users.all %}-->
                        <!--    <i class="fas fa-heart"></i>-->
                        <!--  {% else %}-->
                           <!--아니면  -->
                        <!--    <i class="far fa-heart"></i>-->
                        <!--  {% endif %}-->
                        <!--</a>-->
                        
                        <a href="{% url 'posts:comment_delete' post.id com.id %}"><i class="fas fa-trash-alt"></i></a>
                      </div>
                    {% endfor %}
                      
                      
                        {% load bootstrap4  %}
                        <!-- ModelForm about comment -->
                      <div class="container-fluid">
                        <form method = "POST" action={% url 'posts:comment_create' post.id %}>
                          {% csrf_token  %}
                            <div class="col">
                              <!-- bootstrap form  -->
                              {% bootstrap_form comment_form  %}
                          </div>
                        </form>
                      </div>
                      


                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {% endif  %}
    {% endfor  %}
    
  </div>

</div>

<script type="text/javascript" src="{% static 'accounts/js/script.js' %}"></script>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

<form method="POST">
    {% csrf_token %}
    
    <button class="btn btn-primary">회원가입</button>
    
    {% bootstrap_form form %}
</form>

{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form user_change_form %}
  {% bootstrap_form profile_form %}
    <button class="btn btn-primary">정보 변경</button>
</form>

{% endblock %}