insta/urls.py
from django.contrib import admin
from django.urls import path, include

#upload setting
from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views
from posts import views as posts_views

urlpatterns = [
    path('', posts_views.list, name='root'),
    path('admin/asdf/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:username>', accounts_views.people, name="people"),
    
]


# Dev only
# static(통과하고자 하는 url, 실제 저장 장소)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name="posts"


urlpatterns = [
        path('create/', views.create, name='create'),
        path('', views.list, name="list"),
        path('<int:post_id>/', views.delete, name='delete'),
        path('<int:post_id>/update/', views.update, name='update'),
        path('<int:post_id>/like/', views.like, name='like'),
        path('<int:post_id>/comment/create', views.comment_create, name='comment_create'),
        path('<int:post_id>/<int:comment_id>/delete', views.comment_delete, name='comment_delete'),
    ]

posts/models.py
from django.db import models
#from django.contrib.auth.models import User 직접 접근
from django.conf import settings
from django_extensions.db.models import TimeStampedModel
# django.conf~~!!!!


# Create your models here.
class Post(TimeStampedModel):
    content = models.CharField(max_length=220)
    image = models.ImageField(blank=True)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts', blank=True)
    
    def __str__(self):
        return f"{self.id}: {self.content}"
    
    
class Comment(TimeStampedModel):
    content = models.CharField(max_length=140)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=False)
    
    def __str__(self):
        return f"{self.user}-{self.post}: {self.content}"


# class Comment_Response(models.Model):
#     content = models.CharField(max_length=140)
#     comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='reponses')
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=False)
#     def __str__(self):
#         return f"{self.id}: {self.content}"

posts/forms.py
from django import forms
from .models import Post, Comment


# PostModelForm to manipulate Post model

class PostModelForm(forms.ModelForm):
    # 1. What input fields this form have.
    content = forms.CharField(label="content", widget=forms.Textarea(attrs={
        "placeholder":"What's Up~!"
    }))
    
    
    # 2. To set properties of corresponding inputs.
    class Meta:
        model = Post
        fields = ["content", 'image']


class CommentModelForm(forms.ModelForm):
    content = forms.CharField(label='', widget = forms.TextInput(
        attrs={
            'placeholder':"댓글 달기..."
            
        }))
    
    class Meta:
        model = Comment
        fields = ['content']

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.db.models import Q


from .forms import PostModelForm, CommentModelForm
from .models import Post, Comment
# Create your views here.


def create(request):
    if request.method == "POST":
        # post를 DB에 적용.
        form = PostModelForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            form.save()
            return redirect('posts:list')
        else:
            # error handling
            pass
    else:
        form = PostModelForm()
        return render(request,'posts/create.html',{
            "form":form
        })

@login_required
def list(request):
    # 1. 내가 팔로우한 사람들의 포스트만 보여줌.
    # 2. 내가 작성한 post도 보여줌.
    # Show all the posts.
    
    posts = Post.objects.filter(Q(user=request.user) | Q(user__in=request.user.followings.all()) ).order_by('-created')
    
    context = {
        'posts':posts,
        'comment_form':CommentModelForm()
    }
    return render(request,'posts/list.html', context)


@require_POST
def delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    
    if post.user != request.user:
        return redirect('posts:list')
    post.delete()
    return redirect('posts:list')
        
def update(request, post_id):
    post = Post.objects.get(id=post_id)
    
    if post.user != request.user:
        return redirect('posts:list')
    
    
    if request.method == "POST":
        
        form = PostModelForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:list')
        else:
            # error handling
            pass
    else:
        
        form = PostModelForm(instance=post)
        return render(request, 'posts/create.html', {
            'form':form
        })


@login_required
def like(request, post_id):
    # 1. retrieve the post
    post = get_object_or_404(Post, id=post_id)
    
    #post.like_users.add(request.User)
    # 2. If user already like this post. Undo (Remove Like)
    if request.user in post.like_users.all():
        post.like_users.remove(request.user)
    else:
    # 3. If user did not like this post yet. Like
        post.like_users.add(request.user)
    
    return redirect('posts:list')
    
    
@login_required
@require_POST
def comment_create(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentModelForm(request.POST)
    if form.is_valid():
        com = form.save(commit=False)
        com.post = post
        com.user = request.user
        form.save()
        return redirect('posts:list')


@login_required
def comment_delete(request, post_id, comment_id):
    com = get_object_or_404(Comment, id=comment_id)
    post = get_object_or_404(Post, id=post_id)
    if request.user == com.user or request.user == post.user:
        com.delete()
    return redirect('posts:list')
    
    

posts/templates/posts/create.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<form method="POST" enctype="multipart/form-data">
  <!-- 파일을 보낼 땐, enctype = "multipart/form-data" 추가해야 함.-->
  {% csrf_token %}
  <!--model form-->
  <!--{{ form }}-->
  {%  bootstrap_form form %}
  <button type="submit" class='btn btn-primary'>upload</button>
</form>
{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %}
{% load static %}

{% block title  %}
{{user.username}} Myinstagram
{% endblock  %}


{% block body %}
  <link rel="stylesheet" href="{% static 'posts/css/style.css' %}" type="text/css" />
  
  <div class="row justify-content-center">
    <div class="col-8">
      {% for post in posts %}
            <div class="card m-2" style="width: 40rem;">
                <div class="card-header">
                  <div class="container-fluid">
                    <div class="row">
                      <div class="col-11 p-0">
                        {% if post.user.profile.image %}
                          <img src="{{post.user.profile.image.url}}" height="30" width="30" style="border-radius:50%"></img>
                        {% else %}
                          <img src="{% static 'accounts/img/default_user.png' %}" height="30" width="30" style="border-radius:50%"></img>
                        {% endif %}
                        <strong><a href="{% url 'people' post.user.username %}">{{ post.user.username }}</a></strong>
                      </div>
                      <div class="col-1 p-0 d-flex justify-content-end align-items-center">
                        <i class="fas fa-ellipsis-h" data-toggle="modal" data-target="#post_update{{post.id}}"></i>
                      </div>
                    </div>
                  </div>
                  
                  
                  
                  <!-- Modal at header  -->
                  <div class="modal fade" id="post_update{{post.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-body p-0">
                          <div class="container-fluid p-0">
                            <div class="row p-0 justify-content-center align-items-center">
                              
                              <div class="btn" style='color:red;'>부적절한 컨텐츠 신고</div>
                              
                            </div>
                            <hr>
                            <div class="row p-0 justify-content-center align-items-center">
                              
                              <div class="btn" style='color:red'>팔로우 취소</div>
                              
                            </div>
                            <hr>
                            <div class="row p-0 justify-content-center align-items-center">
                              
                              <div class="btn">게시물로 이동</div>
                              
                            </div>
                            <hr>
                            <div class="row p-0 justify-content-center align-items-center">
                              
                              <div class="btn">링크 복사</div>
                              
                            </div>
                            <hr>
                            <div class="row p-0 justify-content-center align-items-center">
                              
                              <div class="btn">공유하기</div>
                              
                            </div>
                            <hr>
                            <div class="row p-0 justify-content-center align-items-center">
                              
                              <div class="btn">취소</div>
                              
                            </div>

                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  
                </div>
                
                {% if post.image %}
                  <img src="{{post.image.url}}" class="card-img-top user_image" alt="...">
                {% else %}
                  <img src="https://picsum.photos/200/200/?random" class="card-img-top" alt="...">
                {% endif %}
  
              
              <div class="card-body">
                <p class="card-text">{{post.content}}</p>
                
                <!-- 작성자만 수정/삭제 가능  -->
                {% if post.user == request.user  %}
                  <form method="POST" action = "{% url 'posts:delete' post.id %}" class="d-inline-block">
                    {% csrf_token %}
                    <button class="btn btn-danger">삭제</button>
                  </form>
                  <a href="{% url 'posts:update' post.id %}" class="btn btn-success">수정</a>
                {% endif%}
              </div>
              <!--좋아요 버튼 추가-->
              <div class="card-body">
                
                <a href="{% url 'posts:like' post.id %}">
                  <!-- 해당유저가 like를 했으면   -->
                  {% if user in post.like_users.all %}
                    <i class="fas fa-heart"></i>
                  {% else %}
                  <!-- 아니면  -->
                    <i class="far fa-heart"></i>
                  {% endif %}
                </a>
                <a href="#"><i class="far fa-comment-alt"></i></a>
                <a href="#"><i class="far fa-share-square"></i></a>
                
                <p class="card-text">
                  좋아요 {{post.like_users.count}}개
                </p>
              </div>
              
              {% load bootstrap4 %}
              
              <div class="card-body m-0 p-0">
                <!-- 해당글에 작성된 댓글을 모두 출력  -->
                {% for com in post.comments.all  %}
                  <div class="card-text m-1 p-0 d-flex justify-content-between">
                    <div>
                      <strong>{{com.user.username}}</strong>: {{com.content}}
                    </div>
                    <div>
                      <!--<a href="{% url 'posts:like' post.id %}">-->
                        <!-- 해당유저가 like를 했으면   -->
                      <!--  {% if user in post.like_users.all %}-->
                      <!--    <i class="fas fa-heart"></i>-->
                      <!--  {% else %}-->
                        <!-- 아니면  -->
                      <!--    <i class="far fa-heart"></i>-->
                      <!--  {% endif %}-->
                      <!--</a>-->
                      
                      <a href="{% url 'posts:comment_delete' post.id com.id %}"><i class="fas fa-trash-alt"></i></a>
                    </div>
                  </div>
                  
                  
                  {% empty  %}
                  <p>댓글이 없습니다.</p>
                  
                {% endfor %}
                
                <!-- ModelForm about comment -->
                
                <form method = "POST" action={% url 'posts:comment_create' post.id %}>
                  {% csrf_token  %}
                  <div class="row">
                    <div class="col-10">
                      <!-- bootstrap form  -->
                      {% bootstrap_form comment_form  %}
                    </div>
                    <div class="col-2">
                      <button type='submit' class="btn btn-primary">게시</button>
                    </div>
                  </div>
                </form>
                
                
              
              </div>
              
            </div>
      {% endfor %}
    
            
      
    </div>
    
    <!-- User List  -->
    <div class="col-xl-3 m-0">
      <div class="personal_info container-fluid">
        <div class="row mt-4">
          {% if user.profile.image %}
            <img src="{{user.profile.image.url}}" height="150" width="150" style="border-radius:50%"></img>
          {% else %}
            <img src="{% static 'accounts/img/default_user.png' %}" height="150" width="150" style="border-radius:50%"></img>
          {% endif %}
        </div>
        <div class="row mt-2">
          {{user.username}}
          {{user.profile.nickname}}
        </div>
          
        
        <div class="row personal_info_content">
          <div class="title">스토리</div>
          
          <div>회워님이 팔로우하는 사람들의 스토리가 여기에 표시됩니다.</div>
          
        </div>
        <div class="row">
          
          
        </div>
      </div>
    </div>
    
    
  </div>  
  
  <script src="{% static 'posts/js/script1.js' %}"></script>
{% endblock %}